set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH PATH;ZIG_PATH;MACOSSDK)
set(VCPKG_KEEP_ENV_VARS PATH;ZIG_PATH;MACOSSDK)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchain/x64-osx-zig.cmake)
include(${VCPKG_CHAINLOAD_TOOLCHAIN_FILE})

