# Common options for every Zig triplet

set(VCPKG_TARGET_ARCHITECTURE $ENV{ZIG_ARCH})
set(VCPKG_CMAKE_SYSTEM_NAME $ENV{ZIG_OS})
set(VCPKG_CMAKE_SYSTEM_PROCESSOR $ENV{ZIG_ARCH})
set(VCPKG_LIBRARY_LINKAGE $ENV{ZIG_LIB_LINKAGE})
set(VCPKG_CRT_LINKAGE dynamic)
if ($ENV{ZIG_TARGET} MATCHES "windows")
    set(VCPKG_TARGET_IS_WINDOWS ON)
    set(VCPKG_TARGET_IS_MINGW ON)
endif()
set(VCPKG_OSX_ARCHITECTURES $ENV{ZIG_OSX_ARCH})
set(VCPKG_ENV_PASSTHROUGH PATH;ZIG_PATH;ZIG_TARGET;ZIG_LIB_LINKAGE;ZIG_OPTIMIZE;MACOSSDK;DPREFIX)
set(VCPKG_KEEP_ENV_VARS PATH;ZIG_PATH;ZIG_TARGET;ZIG_LIB_LINKAGE;ZIG_OPTIMIZE;MACOSSDK;DPREFIX)
set(VCPKG_BUILD_TYPE $ENV{ZIG_OPTIMIZE})

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchain/zig.cmake)
include(${VCPKG_CHAINLOAD_TOOLCHAIN_FILE})


