const std = @import("std");
pub const Level = enum { err, warn, info, debug, default }; //cannot use std.log.Level because it gets corrupted in options generated file
pub const OutputType = enum { Default, c, IR, BC, None };

pub const Options = struct {
    custom_library: ?[]const []const u8,
    dependencies: bool,
    editor: bool,
    ignore_missing: bool,
    include: ?[]const u8,
    lib_assert: bool,
    lib_debug: bool,
    lib_dir: ?[]const u8,
    lib_linkage: std.builtin.LinkMode,
    linkage: std.builtin.LinkMode,
    llvm: bool,
    log_intercept: bool,
    log_level: Level,
    memory_safety: ?u32,
    output: OutputType,
    sanitize: bool,
    sdk: ?[]const u8,
    stack_check: bool,
    stack_protector: bool,
    strip: bool,
    system_glew: bool,
    system_glfw: bool,
    system_glslang: bool,
    system_nfd: bool,
    system_wolfssl: bool,
    traces: bool,
    triplet: []const u8,
    valgrind: bool,
    unwind: ?std.builtin.UnwindTables,
};
