set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x64)

find_program(ZIG_PATH zig)
get_filename_component(ZIG_DIR ${ZIG_PATH} DIRECTORY)

set(tools ${ZIG_DIR})
set(CMAKE_C_COMPILER ${tools}/zig)
set(CMAKE_CXX_COMPILER ${tools}/zig)

if(NOT ALREADY_HERE EQUAL 1)
    set(ALREADY_HERE 1)
    set(CMAKE_C_COMPILER_ARG1 "cc -target x86_64-windows ${CMAKE_C_COMPILER_ARG1}")
    set(CMAKE_CXX_COMPILER_ARG1 "c++ -target x86_64-windows ${CMAKE_CXX_COMPILER_ARG1}")
endif()

set(CMAKE_RC_COMPILER_INIT ${tools}/zig)
set(CMAKE_RC_COMPILER_ARG1 "rc")
set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -- <SOURCE> <OBJECT>")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)