if(NOT DEFINED $ENV{ZIG_PATH})
    find_program(ZIG_PATH "zig${CMAKE_EXECUTABLE_SUFFIX}")
else()
    set(ZIG_PATH $ENV{ZIG_PATH})
endif()
get_filename_component(ZIG_DIR ${ZIG_PATH} DIRECTORY)


if(NOT ZIG_PATH)
    set(ZIG "zig")
else()
    set(ZIG ${ZIG_PATH})
endif()

set(CMAKE_C_COMPILER "${ZIG}" CACHE FILEPATH "")
set(ENV{ZIG} "${ZIG}")
set(ENV{CC} "${CMAKE_C_COMPILER} cc -target $ENV{ZIG_TARGET}")
set(CMAKE_CXX_COMPILER "${ZIG}" CACHE FILEPATH "")
set(ENV{CXX} "${CMAKE_CXX_COMPILER} c++ -target $ENV{ZIG_TARGET}")

set(BUILD_DIR "${CMAKE_CURRENT_LIST_DIR}/../../build")

if(NOT ALREADY_HERE EQUAL 1)
    set(ALREADY_HERE 1)
    set(CMAKE_C_COMPILER_ARG1 "cc -target $ENV{ZIG_TARGET} ${CMAKE_C_COMPILER_ARG1}" CACHE STRING "")
    set(CMAKE_CXX_COMPILER_ARG1 "c++ -target $ENV{ZIG_TARGET} ${CMAKE_CXX_COMPILER_ARG1}" CACHE STRING "")
    set(CMAKE_AR "${BUILD_DIR}/ar" CACHE FILEPATH "")
endif()

set(CMAKE_RC_COMPILER_INIT "${ZIG}")
set(CMAKE_RC_COMPILER_ARG1 "rc")
set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -- <SOURCE> <OBJECT>")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_PROGRAM_PATH "${BUILD_DIR}/vcpkg_installed/$ENV{ZIG_TARGET}/")